// The shop's rail. 14 garments, 5 colourways each, one photograph per
// garment — not one per colourway.
//
// THE MONEY DECISION: we generate/photograph 14 images, not 70. The
// colourway is applied as a sentence in the try-on prompt at generation
// time ("recoloured to deep wine #6E2639"), which costs nothing and yields
// 70 combinations from 14 files. Do not add a second image per colourway.

export const CATEGORIES = {
  MEN: "men",
  WOMEN: "women",
};

export const GARMENTS = [
  // ---------------- menswear (10) ----------------
  {
    id: "chikankari-kurta-set",
    name: "Chikankari Kurta Set",
    gender: "men",
    category: "kurta-set",
    fabric: "Hand-embroidered chikankari on cotton",
    price: 6800,
    image: "/catalogue/chikankari-kurta-set.jpg",
    colourways: [
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Dusty Rose", hex: "#B8778A" },
      { name: "Midnight Navy", hex: "#1B2438" },
    ],
  },
  {
    id: "silk-bandhgala",
    name: "Silk Bandhgala",
    gender: "men",
    category: "bandhgala",
    fabric: "Raw silk bandhgala with zari piping",
    price: 24500,
    image: "/catalogue/silk-bandhgala.jpg",
    colourways: [
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Peacock Blue", hex: "#0F5C6B" },
    ],
  },
  {
    id: "ivory-sherwani",
    name: "Ivory Sherwani",
    gender: "men",
    category: "sherwani",
    fabric: "Silk-blend sherwani with resham embroidery",
    price: 42000,
    image: "/catalogue/ivory-sherwani.jpg",
    colourways: [
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Maroon", hex: "#5A1B24" },
    ],
  },
  {
    id: "nehru-jacket-set",
    name: "Nehru Jacket Set",
    gender: "men",
    category: "nehru-jacket",
    fabric: "Jacquard silk Nehru jacket over cotton kurta",
    price: 9600,
    image: "/catalogue/nehru-jacket-set.jpg",
    colourways: [
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Rust Copper", hex: "#A6512C" },
      { name: "Deep Teal", hex: "#164B47" },
      { name: "Royal Purple", hex: "#4A2545" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
    ],
  },
  {
    id: "pathani-suit",
    name: "Pathani Suit",
    gender: "men",
    category: "pathani-suit",
    fabric: "Cotton-linen Pathani suit",
    price: 4200,
    image: "/catalogue/pathani-suit.jpg",
    colourways: [
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
    ],
  },
  {
    id: "dhoti-kurta",
    name: "Dhoti Kurta",
    gender: "men",
    category: "dhoti-kurta",
    fabric: "Handloom cotton dhoti kurta",
    price: 5400,
    image: "/catalogue/dhoti-kurta.jpg",
    colourways: [
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Rust Copper", hex: "#A6512C" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Blush Pink", hex: "#D9AFAE" },
    ],
  },
  {
    id: "indo-western-drape-jacket",
    name: "Indo-Western Drape Jacket",
    gender: "men",
    category: "drape-jacket",
    fabric: "Silk drape jacket with asymmetric cowl",
    price: 28000,
    image: "/catalogue/indo-western-drape-jacket.jpg",
    colourways: [
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Deep Teal", hex: "#164B47" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Royal Purple", hex: "#4A2545" },
    ],
  },
  {
    id: "velvet-achkan",
    name: "Velvet Achkan",
    gender: "men",
    category: "achkan",
    fabric: "Silk velvet achkan with zardozi collar",
    price: 58000,
    image: "/catalogue/velvet-achkan.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "linen-kurta-pyjama",
    name: "Linen Kurta Pyjama",
    gender: "men",
    category: "kurta-pyjama",
    fabric: "Pure linen kurta pyjama",
    price: 3400,
    image: "/catalogue/linen-kurta-pyjama.jpg",
    colourways: [
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Dusty Rose", hex: "#B8778A" },
      { name: "Mustard", hex: "#C79A3A" },
    ],
  },
  {
    id: "printed-short-kurta",
    name: "Printed Short Kurta",
    gender: "men",
    category: "short-kurta",
    fabric: "Block-printed cotton short kurta",
    price: 3800,
    image: "/catalogue/printed-short-kurta.jpg",
    colourways: [
      { name: "Rust Copper", hex: "#A6512C" },
      { name: "Peacock Blue", hex: "#0F5C6B" },
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
    ],
  },

  // ---------------- womenswear (4) ----------------
  {
    id: "banarasi-silk-saree",
    name: "Banarasi Silk Saree",
    gender: "women",
    category: "saree",
    fabric: "Pure Banarasi silk with zari border",
    price: 32000,
    image: "/catalogue/banarasi-silk-saree.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Peacock Blue", hex: "#0F5C6B" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Bottle Green", hex: "#1F4235" },
    ],
  },
  {
    id: "floor-length-anarkali",
    name: "Floor-Length Anarkali",
    gender: "women",
    category: "anarkali",
    fabric: "Georgette Anarkali with gota embroidery",
    price: 18500,
    image: "/catalogue/floor-length-anarkali.jpg",
    colourways: [
      { name: "Dusty Rose", hex: "#B8778A" },
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Deep Teal", hex: "#164B47" },
      { name: "Blush Pink", hex: "#D9AFAE" },
      { name: "Royal Purple", hex: "#4A2545" },
    ],
  },
  {
    id: "zardozi-lehenga-choli",
    name: "Zardozi Lehenga Choli",
    gender: "women",
    category: "lehenga-choli",
    fabric: "Zardozi-embroidered raw silk lehenga choli",
    price: 68000,
    image: "/catalogue/zardozi-lehenga-choli.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "chanderi-salwar-kameez",
    name: "Chanderi Salwar Kameez",
    gender: "women",
    category: "salwar-kameez",
    fabric: "Chanderi silk-cotton salwar kameez",
    price: 7200,
    image: "/catalogue/chanderi-salwar-kameez.jpg",
    colourways: [
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Blush Pink", hex: "#D9AFAE" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Dusty Rose", hex: "#B8778A" },
    ],
  },
];

export const byId = (id) => GARMENTS.find((g) => g.id === id);

export const inr = (n) => "₹" + n.toLocaleString("en-IN");
